---

- name: create prometheus group
  group:
    name={{ prometheus_machine_group }}
    state=present
    system=yes

- name: create prometheus user
  user:
    name={{  prometheus_machine_user }}
    group={{ prometheus_machine_group }}
    system=yes
    createhome=no

- name: already installed check
  stat: path={{ prometheus_machine_install_dir }}/node_exporter
  register: binary_file

- name: install - checkout prometheus from github.com
  git:
    repo={{ prometheus_machine_repo }}
    dest={{ prometheus_machine_build_folder }}
    version=master
    depth=1
    update=yes
    accept_hostkey=yes
    force=yes
    recursive=yes

- name: make prometheus
  command: make 
  args:
    chdir: "{{ prometheus_machine_build_folder }}"
  when: not binary_file.stat.exists

- name: make directories
  file:
    state=directory
    path={{ item }}
    owner={{ prometheus_machine_user }}
    group={{ prometheus_machine_group }}
    mode=0755
  with_items:
    - "{{ prometheus_machine_conf_dir }}"
    - "{{ prometheus_machine_log_dir }}"
    - "{{ prometheus_machine_install_dir }}"

- name: move binary
  command: mv {{ prometheus_machine_build_folder }}/node_exporter {{ prometheus_machine_install_dir }}/
  args:
    creates: "{{ prometheus_machine_install_dir }}/node_exporter"


