---

- name: install dependencies
  include: depend.yml

- name: install machine exporter
  include: install.yml

- name: setup machine exporter as runit service and start it
  runit:
    name: "{{ prometheus_machine_service_name }}"
    enabled: true
    state: up
    timeout: 9
    user: "{{ prometheus_machine_user }}"
    command: "{{ prometheus_machine_install_dir }}/node_exporter collectors.enabled=attributes,diskstats,filesystem,loadavg,meminfo,stat,textfile,time,netdev,netstat,runit,lastlogin"

