---

- name: setup machine exporter as runit service and start it
  tags:
    - config # since there's no config, just the startup parms
    - service
  runit:
    name: "{{ prometheus_machine_service_name }}"
    enabled: true
    state: start
    timeout: 9
    user: "{{ prometheus_machine_user }}"
    command: "{{ prometheus_machine_install_dir }}/node_exporter -web.listen-address={{ prometheus_machine_listen_address }} -collectors.enabled={{ prometheus_machine_collectors }}"
  register: prometheus_machine_service_status
