---
# handlers file for prometheus_machine

- name: restart prometheus machine
  runit: 
    name={{ prometheus_machine_service_name }} 
    action=restart
    state=up
    enabled=true
    timeout=9
  when: not prometheus_machine_service_status.restarted


